sources:
 - masters/PendotLSource-Regular.glyphspackage
familyName: "Pendot L Source"

recipe:
  ../fonts/ttf/PendotLTestA-Light.ttf:
    - source: masters/PendotLSource-Regular.glyphspackage
    - operation: exec
      exe: pendot
      args: dot -o build/PendotLDot-Light.glyphs masters/PendotLSource-Regular.glyphspackage Light
    - source: build/PendotLDot-Light.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildTTF
    - operation: rename
      name: Pendot L Dot Test A Light
    - operation: fix

  ../fonts/ttf/PendotLTestA-Regular.ttf:
    - source: masters/PendotLSource-Regular.glyphspackage
    - operation: exec
      exe: pendot
      args: dot -o build/PendotLDot-Regular.glyphs masters/PendotLSource-Regular.glyphspackage Regular
    - source: build/PendotLDot-Regular.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildTTF
    - operation: rename
      name: Pendot L Dot Test A Regular
    - operation: fix

  ../fonts/ttf/PendotLTestA-SemiBold.ttf:
    - source: masters/PendotLSource-Regular.glyphspackage
    - operation: exec
      exe: pendot
      args: dot -o build/PendotLDot-SemiBold.glyphs masters/PendotLSource-Regular.glyphspackage SemiBold
    - source: build/PendotLDot-SemiBold.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildTTF
    - operation: rename
      name: Pendot L Dot Test A SemiBold
    - operation: fix

  ../fonts/ttf/PendotLTestA-Bold.ttf:
    - source: masters/PendotLSource-Regular.glyphspackage
    - operation: exec
      exe: pendot
      args: dot -o build/PendotLDot-Bold.glyphs masters/PendotLSource-Regular.glyphspackage Bold
    - source: build/PendotLDot-Bold.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildTTF
    - operation: rename
      name: Pendot L Dot Test A Bold
    - operation: fix
